import car1 from "./images/car1.jpg";
import car2 from "./images/Mercedes.jpg";
import car3 from "./images/Koenigsegg.jpg";
import car4 from "./images/BMW2.jpg";
import car5 from "./images/BMW1.jpg";
import car6 from "./images/Lamborghini.jpg";
const carData = [
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },

  //page2
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },

  //page3
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  //page4
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  //page5
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  //page6
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  //page7
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  //page8
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  //page9
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  //page10
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  
  {
    name: "BMW M4",
    image: car1,
    model_year: "2023",
    seats: "5",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Lamborghini",
    image: car6,
    model_year: "2023",
    seats: "2",
    fuel_type: "Electric",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "800",
  },
  {
    name: "BMW",
    image: car4,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },
  {
    name: "BMW",
    image: car5,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  },
  {
    name: "Mercedes",
    image: car2,
    model_year: "2023",
    seats: "4",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "600",
  },//page11
  {
    name: "Koenigsegg",
    image: car3,
    model_year: "2023",
    seats: "2",
    fuel_type: "Gasoline",
    mileage: "8.0km/1-litre",
    gear_type: "Automatic",
    rent_price: "400",
  }
  
];
export default carData;
